### PR TITLE
Fix #51

### LINKED ISSUE #51: Improve error message when user tries to add mod through preview URL
Example URL: https://mod.io/g/drg/m/bucks-shitty-audio-modpack?preview=b2af1287d7ec5cae8d7a2994717b639b

The following error occurs when adding the mod:
```
modio::Error {
    kind: Validation(
        "Validation Failed. Please see below to fix invalid input:",
        {
            "name_id": "The \"name id\" may not be greater than 50 characters.",
        },
    ),
}
```

@jieyouxu can you see if you can replicate? it works for truman, but it could be because his account automatically has access to everything due to being a community moderator.

### PR DESCRIPTION
**Pull request by Buckminsterfullerene02**

### CODE REVIEW

File: src/providers/modio.rs [hunk 1]
```diff
@@ -211,6 +211,10 @@ impl ModProvider for ModioProvider {
         use modio::filter::{Eq, In};
         use modio::mods::filters::{Id, NameId, Visible};
 
+        if spec.url.contains("?preview=") {
+            return Err(anyhow!("Preview mod links cannot be added directly, please subscribe to the mod on mod.io and use the subscription link instead."));
```
Comment (trumank) [inline src/providers/modio.rs:215]: Perhaps "[...] and then use the non-preview link." would be better phrasing?

Comment (Buckminsterfullerene02) [reply src/providers/modio.rs:215]: Sure.
